import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
// import {  ClerkProvider} from '@clerk/nextjs'
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import NavbarMain from "@/components/common/Navbar/NavbarMain";
import Footer  from "@/components/common/Footer/Footer";
const grotesk = Space_Grotesk({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Deval Ride App | geet Instant Rides to your Desitination",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>

    <html lang="en">
      <body className={`${grotesk.className} antialiased relative`}>
        <NavbarMain />
        {children}
        <Footer />
        <Toaster />
      </body>
    </html>
    // </ClerkProvider>
  );
}
