import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
// import {  ClerkProvider} from '@clerk/nextjs'
import "./globals.css";
import Navbar from "@/components/common/Navbar/NavbarDesktop";
const grotesk = Space_Grotesk({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>

    <html lang="en">
      <body className={`${grotesk.className} antialiased relative`}>
        <Navbar />
        {children}
      </body>
    </html>
    // </ClerkProvider>
  );
}
